services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome@1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  eureka-server:
    image: komalsingh26/eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    networks:
      - app-network

  #  config-server:
  #    image: komalsingh26/config-server:22.09.2025
  #    container_name: config-server
  #    depends_on:
  #      - eureka-server
  #    ports:
  #      - "8888:8888"
  #    environment:
  #      SPRING_APPLICATION_NAME: config-server
  #      SPRING_PROFILES_ACTIVE: docker
  #      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  #    networks:
  #      - app-network


  identity-service:
    image: komalsingh26/identity-service:1.2
    container_name: identity-service
    depends_on:
      - postgres
      - eureka-server
    #      - config-server
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_NAME: identity-service
      #      SPRING_PROFILES_ACTIVE: docker
      #      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/identity_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Welcome@1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-network

  user-service:
    image: komalsingh26/user-service:1.2
    container_name: user-service
    depends_on:
      - postgres
      - eureka-server
    #      - config-server
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: user-service
      #      SPRING_PROFILES_ACTIVE: docker
      #      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Welcome@1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
    networks:
      - app-network

  ticket-service:
    image: komalsingh26/ticket-service:1.3
    container_name: ticket-service
    depends_on:
      - postgres
      - eureka-server
    #      - config-server
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: ticket-service
      #      SPRING_PROFILES_ACTIVE: docker
      #      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticket_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Welcome@1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - app-network

  api-gateway-service:
    image: komalsingh26/api-gateway-service:1.2
    container_name: api-gateway-service
    depends_on:
      - eureka-server
      - identity-service
      - user-service
    #      - config-server
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: api-gateway-service
      #      SPRING_PROFILES_ACTIVE: docker
      #      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
    external: true
